LABELS = [
    'timestamp',
    'number_of_announce',
    'number_of_withdrawal',
    'number_of_announce_NLRI_prefix',
    'number_of_withdrawn_NLRI_prefix',
    'average_ASpath_length',
    'maximum_ASpath_length',
    'average_unique_ASpath_length',
    'number_of_duplicate_announcements',
    'number_of_duplicate_withdrawals',
    'number_of_implicit_withdraw',
    'average_edit_distance',
    'maximum_edit_distance',
    'inter_arrival_time',
    'number_of_edit_distance_7',
    'number_of_edit_distance_8',
    'number_of_edit_distance_9',
    'number_of_edit_distance_10',
    'number_of_edit_distance_11',
    'number_of_edit_distance_12',
    'number_of_edit_distance_13',
    'number_of_edit_distance_14',
    'number_of_edit_distance_15',
    'number_of_edit_distance_16',
    'number_of_edit_distance_17',
    'number_of_ASpath_length_7',
    'number_of_ASpath_length_8',
    'number_of_ASpath_length_9',
    'number_of_ASpath_length_10',
    'number_of_ASpath_length_11',
    'number_of_ASpath_length_12',
    'number_of_ASpath_length_13',
    'number_of_ASpath_length_14',
    'number_of_ASpath_length_15',
    'number_of_IGP_packets',
    'number_of_EGP_packets',
    'number_of_INCOMPLETE_packagets',
    'packet_size',
    'class',
]

ANOMALY_RANGE = {
  'slammer' => {from: '2003-01-25T05:31:00+00:00', to: '2003-01-25T19:59:00+00:00'},
  'nimda' => {from: '2001-09-18T13:19:00+00:00', to: '2001-09-20T23:59:00+00:00'},
  'coderedi' => {from: '2001-07-19T13:20:00+00:00', to: '2001-07-19T23:19:00+00:00'}
}

DATASETS = ['nimda', 'slammer', 'coderedi']
